// Admin v2 — new data model.
// In production: replace with API (TanStack Query / tRPC).

export const SEED_QUESTIONS = [
  {
    id: 'bq1',
    type: 'multiple-choice',
    text: 'What is the maximum file size allowed for a single product image on Droppii?',
    options: ['2 MB', '5 MB', '10 MB', '20 MB'],
    correct: [1],
    explanation: 'Droppii allows up to 5 MB per image for optimal display quality across devices.',
    points: 1,
  },
  {
    id: 'bq2',
    type: 'true-false',
    text: 'Sellers can list the same product under multiple categories at the same time.',
    options: ['True', 'False'],
    correct: [0],
    explanation: 'Yes — products can appear in multiple relevant categories to increase discoverability.',
    points: 1,
  },
  {
    id: 'bq3',
    type: 'multi-select',
    text: 'Which of the following are required fields when creating a new product listing? (Select all that apply)',
    options: ['Product name', 'Price', 'Stock quantity', 'Product video'],
    correct: [0, 1, 2],
    explanation: 'Product name, price, and stock quantity are mandatory. A product video is optional.',
    points: 2,
  },
  {
    id: 'bq4',
    type: 'short-answer',
    text: 'What is the standard maximum response time (in hours) sellers must meet for customer inquiries on Droppii?',
    keywords: '24, 24 hours, 24h, one day',
    explanation: 'Sellers must respond within 24 hours to maintain their service quality rating.',
    points: 1,
  },
  {
    id: 'bq5',
    type: 'multiple-choice',
    text: 'A buyer requests a return 8 days after delivery. The return policy window is 7 days. What is the correct response?',
    options: [
      'Accept the return — always side with the buyer',
      'Decline the return — outside the 7-day window',
      'Escalate to Droppii support for a policy exception',
      'Offer a 50% refund as a compromise',
    ],
    correct: [1],
    explanation: 'The standard return window is 7 days. Requests outside this window should be politely declined per policy.',
    points: 1,
  },
];

export const MOCK_USER = {
  name: 'An Nguyễn',
  email: 'an@droppii.vn',
  initials: 'AN',
  role: 'Admin',
};

export const CATEGORIES = [
  'Onboarding',
  'Listings',
  'Service',
  'Operations',
  'Compliance',
  'Marketing',
];

// Availability helpers
export function makeAlways() {
  return { type: 'always' };
}

export function makeWindow(opens, closes) {
  return {
    type: 'window',
    opens,
    closes,
    tz: 'Asia/Ho_Chi_Minh',
    autoSubmitOnClose: false,
    reminder15min: true,
  };
}

export const INITIAL_TESTS = [
  {
    id: 't1',
    title: 'Seller Onboarding Assessment',
    category: 'Onboarding',
    description: 'Covers platform basics, listing rules, and seller responsibilities.',
    status: 'published',
    questions: 5,
    questionsList: SEED_QUESTIONS,
    duration: 30,
    passingScore: 70,
    maxAttempts: 'unlimited',
    availability: makeAlways(),
    assignedUsers: 'all',
    randomizeQuestions: true,
    randomizeOptions: true,
    showCorrectAnswers: true,
    requireWebcam: false,
    attempts: 1247,
    avgScore: 78,
    passRate: 84,
    updatedAt: '2 hours ago',
  },
  {
    id: 't2',
    title: 'Product Listing Quality Test',
    category: 'Listings',
    description: 'Evaluates knowledge of listing standards and image requirements.',
    status: 'published',
    questions: 18,
    questionsList: [],
    duration: 25,
    passingScore: 70,
    maxAttempts: 3,
    availability: makeAlways(),
    assignedUsers: 'all',
    randomizeQuestions: true,
    randomizeOptions: true,
    showCorrectAnswers: true,
    requireWebcam: false,
    attempts: 892,
    avgScore: 71,
    passRate: 68,
    updatedAt: 'Yesterday',
  },
  {
    id: 't3',
    title: 'Customer Service Standards',
    category: 'Service',
    description: '',
    status: 'draft',
    questions: 30,
    questionsList: [],
    duration: 45,
    passingScore: 75,
    maxAttempts: 'unlimited',
    availability: makeAlways(),
    assignedUsers: 'all',
    randomizeQuestions: true,
    randomizeOptions: false,
    showCorrectAnswers: false,
    requireWebcam: false,
    attempts: 0,
    avgScore: 0,
    passRate: 0,
    updatedAt: '3 days ago',
  },
  {
    id: 't4',
    title: 'Logistics & Shipping Knowledge',
    category: 'Operations',
    description: '',
    status: 'published',
    questions: 22,
    questionsList: [],
    duration: 35,
    passingScore: 70,
    maxAttempts: 'unlimited',
    availability: makeAlways(),
    assignedUsers: 'all',
    randomizeQuestions: true,
    randomizeOptions: true,
    showCorrectAnswers: true,
    requireWebcam: false,
    attempts: 654,
    avgScore: 82,
    passRate: 91,
    updatedAt: '1 week ago',
  },
  {
    id: 't5',
    title: 'Platform Policies Quiz (2026 update)',
    category: 'Compliance',
    description: 'Updated for the 2026 policy changes.',
    status: 'scheduled',
    questions: 15,
    questionsList: [],
    duration: 20,
    passingScore: 80,
    maxAttempts: 2,
    availability: makeWindow('2026-05-07T19:00', '2026-05-07T20:00'),
    assignedUsers: 'all',
    randomizeQuestions: true,
    randomizeOptions: true,
    showCorrectAnswers: true,
    requireWebcam: false,
    attempts: 0,
    avgScore: 0,
    passRate: 0,
    updatedAt: '4 days ago',
  },
  {
    id: 't6',
    title: 'Marketing Tools Proficiency',
    category: 'Marketing',
    description: '',
    status: 'draft',
    questions: 12,
    questionsList: [],
    duration: 20,
    passingScore: 70,
    maxAttempts: 'unlimited',
    availability: makeAlways(),
    assignedUsers: 'all',
    randomizeQuestions: false,
    randomizeOptions: false,
    showCorrectAnswers: true,
    requireWebcam: false,
    attempts: 0,
    avgScore: 0,
    passRate: 0,
    updatedAt: '2 weeks ago',
  },
  {
    id: 't7',
    title: 'Returns & Refunds Procedure',
    category: 'Service',
    description: '',
    status: 'archived',
    questions: 16,
    questionsList: [],
    duration: 25,
    passingScore: 70,
    maxAttempts: 'unlimited',
    availability: makeAlways(),
    assignedUsers: 'all',
    randomizeQuestions: true,
    randomizeOptions: true,
    showCorrectAnswers: true,
    requireWebcam: false,
    attempts: 412,
    avgScore: 74,
    passRate: 79,
    updatedAt: '1 month ago',
  },
  {
    id: 't8',
    title: 'Live Stream Selling Basics',
    category: 'Marketing',
    description: '',
    status: 'published',
    questions: 20,
    questionsList: [],
    duration: 30,
    passingScore: 70,
    maxAttempts: 'unlimited',
    availability: makeAlways(),
    assignedUsers: 'all',
    randomizeQuestions: true,
    randomizeOptions: true,
    showCorrectAnswers: true,
    requireWebcam: false,
    attempts: 538,
    avgScore: 69,
    passRate: 65,
    updatedAt: '5 days ago',
  },
];

export const INITIAL_QUESTION_BANK = [
  { id: 'q1', text: 'What is the maximum file size for product images on Droppii?',            type: 'multiple-choice', category: 'Listings',    difficulty: 'Easy',   usedInCount: 3 },
  { id: 'q2', text: 'A customer requests a return after 14 days. What is the correct policy?', type: 'multiple-choice', category: 'Service',     difficulty: 'Medium', usedInCount: 2 },
  { id: 'q3', text: 'Describe the steps for setting up a flash sale.',                         type: 'short-answer',   category: 'Marketing',   difficulty: 'Hard',   usedInCount: 1 },
  { id: 'q4', text: 'Match each shipping tier to its delivery time.',                          type: 'matching',       category: 'Operations',  difficulty: 'Medium', usedInCount: 2 },
  { id: 'q5', text: 'Sellers must respond to customer messages within ___ hours.',             type: 'fill-blank',     category: 'Service',     difficulty: 'Easy',   usedInCount: 4 },
  { id: 'q6', text: 'Which of the following are prohibited product categories? (Select all)',   type: 'multi-select',   category: 'Compliance',  difficulty: 'Medium', usedInCount: 2 },
  { id: 'q7', text: 'True or false: All product reviews must be moderated within 24 hours.',   type: 'true-false',     category: 'Service',     difficulty: 'Easy',   usedInCount: 1 },
  { id: 'q8', text: 'Calculate the seller commission for a product priced at 500,000 VND.',    type: 'short-answer',   category: 'Operations',  difficulty: 'Hard',   usedInCount: 0 },
];

export const ACTIVITY = [
  { who: 'Linh Pham',  what: 'completed', target: 'Seller Onboarding Assessment', score: 92, when: '2m ago'  },
  { who: 'Minh Tran',  what: 'completed', target: 'Product Listing Quality',       score: 67, when: '14m ago' },
  { who: 'You',        what: 'published',  target: 'Live Stream Selling Basics',    score: null, when: '1h ago' },
  { who: 'Hoa Le',     what: 'completed', target: 'Logistics & Shipping',           score: 88, when: '2h ago'  },
  { who: 'Tuan Hoang', what: 'failed',    target: 'Logistics & Shipping',           score: 58, when: '6h ago'  },
];
