// Admin v2 — new data model.
// In production: replace with API (TanStack Query / tRPC).

export const MOCK_USER = {
  name: 'An Nguyễn',
  email: 'an@droppii.vn',
  initials: 'AN',
  role: 'Admin',
};

export const CATEGORIES = [
  'Onboarding',
  'Listings',
  'Service',
  'Operations',
  'Compliance',
  'Marketing',
];

// Availability helpers
export function makeAlways() {
  return { type: 'always' };
}

export function makeWindow(opens, closes) {
  return {
    type: 'window',
    opens,
    closes,
    tz: 'Asia/Ho_Chi_Minh',
    autoSubmitOnClose: false,
    reminder15min: true,
  };
}

export const INITIAL_TESTS = [
  {
    id: 't1',
    title: 'Seller Onboarding Assessment',
    category: 'Onboarding',
    description: 'Covers platform basics, listing rules, and seller responsibilities.',
    status: 'published',
    questions: 24,
    duration: 30,
    passingScore: 70,
    maxAttempts: 'unlimited',
    availability: makeAlways(),
    randomizeQuestions: true,
    randomizeOptions: true,
    showCorrectAnswers: true,
    requireWebcam: false,
    attempts: 1247,
    avgScore: 78,
    passRate: 84,
    updatedAt: '2 hours ago',
  },
  {
    id: 't2',
    title: 'Product Listing Quality Test',
    category: 'Listings',
    description: 'Evaluates knowledge of listing standards and image requirements.',
    status: 'published',
    questions: 18,
    duration: 25,
    passingScore: 70,
    maxAttempts: 3,
    availability: makeAlways(),
    randomizeQuestions: true,
    randomizeOptions: true,
    showCorrectAnswers: true,
    requireWebcam: false,
    attempts: 892,
    avgScore: 71,
    passRate: 68,
    updatedAt: 'Yesterday',
  },
  {
    id: 't3',
    title: 'Customer Service Standards',
    category: 'Service',
    description: '',
    status: 'draft',
    questions: 30,
    duration: 45,
    passingScore: 75,
    maxAttempts: 'unlimited',
    availability: makeAlways(),
    randomizeQuestions: true,
    randomizeOptions: false,
    showCorrectAnswers: false,
    requireWebcam: false,
    attempts: 0,
    avgScore: 0,
    passRate: 0,
    updatedAt: '3 days ago',
  },
  {
    id: 't4',
    title: 'Logistics & Shipping Knowledge',
    category: 'Operations',
    description: '',
    status: 'published',
    questions: 22,
    duration: 35,
    passingScore: 70,
    maxAttempts: 'unlimited',
    availability: makeAlways(),
    randomizeQuestions: true,
    randomizeOptions: true,
    showCorrectAnswers: true,
    requireWebcam: false,
    attempts: 654,
    avgScore: 82,
    passRate: 91,
    updatedAt: '1 week ago',
  },
  {
    id: 't5',
    title: 'Platform Policies Quiz (2026 update)',
    category: 'Compliance',
    description: 'Updated for the 2026 policy changes.',
    status: 'scheduled',
    questions: 15,
    duration: 20,
    passingScore: 80,
    maxAttempts: 2,
    availability: makeWindow('2026-05-07T19:00', '2026-05-07T20:00'),
    randomizeQuestions: true,
    randomizeOptions: true,
    showCorrectAnswers: true,
    requireWebcam: false,
    attempts: 0,
    avgScore: 0,
    passRate: 0,
    updatedAt: '4 days ago',
  },
  {
    id: 't6',
    title: 'Marketing Tools Proficiency',
    category: 'Marketing',
    description: '',
    status: 'draft',
    questions: 12,
    duration: 20,
    passingScore: 70,
    maxAttempts: 'unlimited',
    availability: makeAlways(),
    randomizeQuestions: false,
    randomizeOptions: false,
    showCorrectAnswers: true,
    requireWebcam: false,
    attempts: 0,
    avgScore: 0,
    passRate: 0,
    updatedAt: '2 weeks ago',
  },
  {
    id: 't7',
    title: 'Returns & Refunds Procedure',
    category: 'Service',
    description: '',
    status: 'archived',
    questions: 16,
    duration: 25,
    passingScore: 70,
    maxAttempts: 'unlimited',
    availability: makeAlways(),
    randomizeQuestions: true,
    randomizeOptions: true,
    showCorrectAnswers: true,
    requireWebcam: false,
    attempts: 412,
    avgScore: 74,
    passRate: 79,
    updatedAt: '1 month ago',
  },
  {
    id: 't8',
    title: 'Live Stream Selling Basics',
    category: 'Marketing',
    description: '',
    status: 'published',
    questions: 20,
    duration: 30,
    passingScore: 70,
    maxAttempts: 'unlimited',
    availability: makeAlways(),
    randomizeQuestions: true,
    randomizeOptions: true,
    showCorrectAnswers: true,
    requireWebcam: false,
    attempts: 538,
    avgScore: 69,
    passRate: 65,
    updatedAt: '5 days ago',
  },
];

export const INITIAL_QUESTION_BANK = [
  { id: 'q1', text: 'What is the maximum file size for product images on Droppii?',            type: 'multiple-choice', category: 'Listings',    difficulty: 'Easy',   usedInCount: 3 },
  { id: 'q2', text: 'A customer requests a return after 14 days. What is the correct policy?', type: 'multiple-choice', category: 'Service',     difficulty: 'Medium', usedInCount: 2 },
  { id: 'q3', text: 'Describe the steps for setting up a flash sale.',                         type: 'short-answer',   category: 'Marketing',   difficulty: 'Hard',   usedInCount: 1 },
  { id: 'q4', text: 'Match each shipping tier to its delivery time.',                          type: 'matching',       category: 'Operations',  difficulty: 'Medium', usedInCount: 2 },
  { id: 'q5', text: 'Sellers must respond to customer messages within ___ hours.',             type: 'fill-blank',     category: 'Service',     difficulty: 'Easy',   usedInCount: 4 },
  { id: 'q6', text: 'Which of the following are prohibited product categories? (Select all)',   type: 'multi-select',   category: 'Compliance',  difficulty: 'Medium', usedInCount: 2 },
  { id: 'q7', text: 'True or false: All product reviews must be moderated within 24 hours.',   type: 'true-false',     category: 'Service',     difficulty: 'Easy',   usedInCount: 1 },
  { id: 'q8', text: 'Calculate the seller commission for a product priced at 500,000 VND.',    type: 'short-answer',   category: 'Operations',  difficulty: 'Hard',   usedInCount: 0 },
];

export const ACTIVITY = [
  { who: 'Linh Pham',  what: 'completed', target: 'Seller Onboarding Assessment', score: 92, when: '2m ago'  },
  { who: 'Minh Tran',  what: 'completed', target: 'Product Listing Quality',       score: 67, when: '14m ago' },
  { who: 'You',        what: 'published',  target: 'Live Stream Selling Basics',    score: null, when: '1h ago' },
  { who: 'Hoa Le',     what: 'completed', target: 'Logistics & Shipping',           score: 88, when: '2h ago'  },
  { who: 'Tuan Hoang', what: 'failed',    target: 'Logistics & Shipping',           score: 58, when: '6h ago'  },
];
