// Sample admin data for prototype — Vietnamese, 50K seller scale.
window.ADMIN = {
  org: {
    name: "Droppii Business",
    region_count: 8,
    seller_count: 52481,
    active_tests: 3,
  },
  current_admin: {
    name: "Trần Hoàng Quân",
    email: "quan.tran@droppii.vn",
    role: "Quản trị viên",
    initials: "QT",
  },
  kpis: {
    sellers_total: 52481,
    sellers_certified: 38927,
    pass_rate: 74.2,
    pass_rate_delta: +3.8,
    avg_score: 81.6,
    avg_score_delta: +1.2,
    avg_time_min: 24.7,
    avg_time_delta: -1.4,
    drop_off_rate: 8.3,
    drop_off_delta: -1.1,
  },
  tests: [
    { id: "DRP-AI-2026", name: "Kiến thức AI cho Nhà bán hàng — 2026", status: "Đang mở", taken: 38421, pass_rate: 74.2, updated: "2 ngày trước", questions: 20, duration_min: 30, pass_score: 70, type: "Định kỳ" },
    { id: "DRP-TPCN-Q1", name: "Tư vấn TPCN — Tình huống lâm sàng", status: "Đang mở", taken: 12903, pass_rate: 68.5, updated: "1 tuần trước", questions: 15, duration_min: 25, pass_score: 75, type: "Định kỳ" },
    { id: "DRP-PROD-26", name: "Kiến thức sản phẩm Q2/2026", status: "Đang mở", taken: 8217, pass_rate: 82.1, updated: "3 ngày trước", questions: 25, duration_min: 35, pass_score: 70, type: "Bắt buộc" },
    { id: "DRP-ETHIC-25", name: "Đạo đức nghề nghiệp — 2025", status: "Đã lưu trữ", taken: 49120, pass_rate: 91.4, updated: "8 tháng trước", questions: 18, duration_min: 25, pass_score: 70, type: "Định kỳ" },
    { id: "DRP-NEW-26", name: "Onboarding — Người bán mới T05", status: "Bản nháp", taken: 0, pass_rate: 0, updated: "Hôm nay", questions: 12, duration_min: 20, pass_score: 60, type: "Bắt buộc" },
  ],
  // pass-rate over time (weeks)
  pass_rate_series: [62, 64, 63, 67, 69, 68, 71, 70, 72, 74, 73, 75, 74.2],
  // score histogram bins (0-10, 11-20, ... 91-100)
  histogram: [120, 240, 480, 920, 1840, 3210, 5420, 7980, 9210, 6850, 2780],
  // topic mastery — sellers (rows) x topics (cols), values = % correct
  topics: ["Cơ bản AI", "Đạo đức", "Lâm sàng", "Sản phẩm", "Tư vấn"],
  cohorts: [
    { name: "T05/2026", takers: 14821, pass: 78.2 },
    { name: "T04/2026", takers: 13204, pass: 73.5 },
    { name: "T03/2026", takers: 11982, pass: 71.0 },
    { name: "T02/2026", takers: 9421, pass: 68.4 },
  ],
  recent_activity: [
    { who: "Nguyễn Thị Mai Anh", id: "DRP-58294", action: "đậu", test: "DRP-AI-2026", score: 88, when: "2 phút trước", region: "Hà Nội" },
    { who: "Trần Văn Hùng", id: "DRP-41205", action: "đậu", test: "DRP-AI-2026", score: 92, when: "5 phút trước", region: "TP.HCM" },
    { who: "Lê Thị Phương", id: "DRP-12089", action: "rớt", test: "DRP-TPCN-Q1", score: 64, when: "8 phút trước", region: "Đà Nẵng" },
    { who: "Phạm Quốc Bảo", id: "DRP-77103", action: "đang làm", test: "DRP-AI-2026", score: null, when: "12 phút trước", region: "Cần Thơ" },
    { who: "Hoàng Minh Tú", id: "DRP-32480", action: "đậu", test: "DRP-PROD-26", score: 84, when: "18 phút trước", region: "Hải Phòng" },
    { who: "Đỗ Thị Lan", id: "DRP-66201", action: "đậu", test: "DRP-AI-2026", score: 76, when: "21 phút trước", region: "Hà Nội" },
  ],
  // question-bank sample
  question_bank: [
    { id: "Q-0142", topic: "Lâm sàng", type: "Tình huống", difficulty: "Khó", correct_rate: 62.1, used_in: 3, stem: "Nam 55t, đái tháo đường type 2, đang Metformin 1000mg/ngày..." },
    { id: "Q-0098", topic: "Đạo đức", type: "Multi-select", difficulty: "Vừa", correct_rate: 71.4, used_in: 5, stem: "Khi dùng AI để soạn nội dung tư vấn cho khách, điều nào BẮT BUỘC?" },
    { id: "Q-0203", topic: "Cơ bản AI", type: "Single", difficulty: "Dễ", correct_rate: 88.9, used_in: 7, stem: "AI hỗ trợ Nhà bán hàng Droppii hiệu quả nhất ở khâu nào?" },
    { id: "Q-0311", topic: "Sản phẩm", type: "Single", difficulty: "Vừa", correct_rate: 74.0, used_in: 4, stem: "Sản phẩm Omega-3 Droppii Premium phù hợp nhất với đối tượng nào?" },
    { id: "Q-0455", topic: "Tư vấn", type: "Tình huống", difficulty: "Khó", correct_rate: 58.2, used_in: 2, stem: "Khách 35t mới sinh con thứ 2, hỏi về TPCN bổ sung canxi..." },
    { id: "Q-0512", topic: "Đạo đức", type: "Single", difficulty: "Dễ", correct_rate: 92.1, used_in: 6, stem: "Trong trường hợp nào KHÔNG được sử dụng AI để tư vấn?" },
    { id: "Q-0588", topic: "Lâm sàng", type: "Short text", difficulty: "Khó", correct_rate: 45.3, used_in: 1, stem: "Hãy mô tả 3 dấu hiệu bệnh nhân tiểu đường type 2 cần được giới thiệu khám bác sĩ..." },
    { id: "Q-0621", topic: "Cơ bản AI", type: "Multi-select", difficulty: "Vừa", correct_rate: 67.8, used_in: 4, stem: "Những hạn chế nào AI có thể gặp khi tư vấn TPCN?" },
  ],
  sellers: [
    { id:"DRP-58294", name:"Nguyễn Thị Mai Anh", region:"Hà Nội", joined:"03/2024", tests:5, certified:4, last_score:88, status:"Hoạt động" },
    { id:"DRP-41205", name:"Trần Văn Hùng", region:"TP.HCM", joined:"06/2023", tests:8, certified:7, last_score:92, status:"Hoạt động" },
    { id:"DRP-12089", name:"Lê Thị Phương", region:"Đà Nẵng", joined:"01/2025", tests:3, certified:1, last_score:64, status:"Cần ôn lại" },
    { id:"DRP-77103", name:"Phạm Quốc Bảo", region:"Cần Thơ", joined:"09/2024", tests:4, certified:3, last_score:null, status:"Đang thi" },
    { id:"DRP-32480", name:"Hoàng Minh Tú", region:"Hải Phòng", joined:"11/2022", tests:12, certified:11, last_score:84, status:"Hoạt động" },
    { id:"DRP-66201", name:"Đỗ Thị Lan", region:"Hà Nội", joined:"04/2024", tests:5, certified:5, last_score:76, status:"Hoạt động" },
    { id:"DRP-90014", name:"Vũ Quang Anh", region:"TP.HCM", joined:"02/2025", tests:2, certified:0, last_score:58, status:"Cần ôn lại" },
    { id:"DRP-44556", name:"Bùi Thuỳ Trang", region:"Nghệ An", joined:"07/2024", tests:6, certified:5, last_score:81, status:"Hoạt động" },
  ],
  // per-question difficulty for the active test
  question_perf: [
    { n:1, topic:"Cơ bản AI", correct:91, avg_time:38, flag:null },
    { n:2, topic:"Đạo đức", correct:78, avg_time:62, flag:null },
    { n:3, topic:"Cơ bản AI", correct:84, avg_time:45, flag:null },
    { n:4, topic:"Đạo đức", correct:69, avg_time:71, flag:null },
    { n:5, topic:"Sản phẩm", correct:88, avg_time:42, flag:null },
    { n:6, topic:"Sản phẩm", correct:73, avg_time:55, flag:null },
    { n:7, topic:"Lâm sàng", correct:54, avg_time:118, flag:"Khó bất thường" },
    { n:8, topic:"Lâm sàng", correct:68, avg_time:88, flag:null },
    { n:9, topic:"Tư vấn", correct:72, avg_time:64, flag:null },
    { n:10, topic:"Tư vấn", correct:48, avg_time:95, flag:"Khó bất thường" },
    { n:11, topic:"Cơ bản AI", correct:82, avg_time:50, flag:null },
    { n:12, topic:"Đạo đức", correct:91, avg_time:35, flag:null },
    { n:13, topic:"Sản phẩm", correct:79, avg_time:48, flag:null },
    { n:14, topic:"Lâm sàng", correct:65, avg_time:82, flag:null },
    { n:15, topic:"Tư vấn", correct:58, avg_time:78, flag:null },
    { n:16, topic:"Cơ bản AI", correct:86, avg_time:40, flag:null },
    { n:17, topic:"Đạo đức", correct:81, avg_time:55, flag:null },
    { n:18, topic:"Sản phẩm", correct:77, avg_time:52, flag:null },
    { n:19, topic:"Lâm sàng", correct:62, avg_time:90, flag:null },
    { n:20, topic:"Tư vấn", correct:74, avg_time:60, flag:null },
  ],
};
